language: python
#sudo: false
# choose python versions
python:
  - "3.6"
  - "3.7"
  - "2.7"
env:
  - TEST_TARGET=unit PYTHON_TARGET=3.6
  # - TEST_TARGET=integration

install:

  # Install miniconda
  # -----------------
  - if [[ $PYTHON_TARGET == 2* ]]; then
      export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda2;
    else
      export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3;
    fi
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$PYTHON_TARGET
  - source activate $ENV_NAME

  # Customise the testing environment
  # ---------------------------------
  - conda install -c conda-forge --quiet --file conda_requirements.txt
  - conda install -c conda-forge --quiet pytest
  - PREFIX=$HOME/miniconda/envs/$ENV_NAME

  # Output debug info
  - conda list
  - conda info -a

  # Install
  - pip install .

  # Output debug info
  - conda list

# command to run tests
#script
script:
  - pytest
